import type { Student } from './types';
import { students, genId } from './store';

const SEED_KEY = 'msg_seeded_v2';

export function seedStudentsIfNeeded() {
  if (localStorage.getItem(SEED_KEY)) return false;
  const existing = students.get();
  if (existing.length > 0) { localStorage.setItem(SEED_KEY, '1'); return false; }

  const now = new Date().toISOString();
  const data: Student[] = [
    // University
    { id: genId(), name: 'Samod Atanda', level: 'university', school: '', classYear: '500 Level', mentorName: 'Dr. Deji Olajide', mentorPhone: '', mentorEmail: '', feeStatus: 'na', totalFee: 0, feePaid: 0, phone: '', guardianName: '', guardianPhone: '', lastResult: '', lastFollowUp: '', nextFollowUp: '', notes: '', status: 'active', createdAt: now, updatedAt: now },
    { id: genId(), name: 'Oluwadarasimi Taiwo', level: 'university', school: '', classYear: '400 Level', mentorName: 'Mrs. Gbadebo', mentorPhone: '', mentorEmail: '', feeStatus: 'na', totalFee: 0, feePaid: 0, phone: '', guardianName: '', guardianPhone: '', lastResult: '', lastFollowUp: '', nextFollowUp: '', notes: '', status: 'active', createdAt: now, updatedAt: now },
    { id: genId(), name: 'Samuel Oluwawamiri', level: 'university', school: '', classYear: '200 Level', mentorName: 'Prof. Peter Ekeh', mentorPhone: '', mentorEmail: '', feeStatus: 'na', totalFee: 0, feePaid: 0, phone: '', guardianName: '', guardianPhone: '', lastResult: '', lastFollowUp: '', nextFollowUp: '', notes: '', status: 'active', createdAt: now, updatedAt: now },
    { id: genId(), name: 'Ayomide Aina', level: 'university', school: '', classYear: '400 Level', mentorName: 'Ms. Adebola Gbadebo', mentorPhone: '', mentorEmail: '', feeStatus: 'na', totalFee: 0, feePaid: 0, phone: '', guardianName: '', guardianPhone: '', lastResult: '', lastFollowUp: '', nextFollowUp: '', notes: '', status: 'active', createdAt: now, updatedAt: now },
    { id: genId(), name: 'Oluwasegun Akinwale', level: 'university', school: '', classYear: '200 Level', mentorName: 'Dr. Folasade Kehinde', mentorPhone: '', mentorEmail: '', feeStatus: 'na', totalFee: 0, feePaid: 0, phone: '', guardianName: '', guardianPhone: '', lastResult: '', lastFollowUp: '', nextFollowUp: '', notes: '', status: 'active', createdAt: now, updatedAt: now },
    { id: genId(), name: 'Abatan Oluwabusola', level: 'university', school: '', classYear: '300 Level', mentorName: 'Dr. Foluke Otitoju', mentorPhone: '', mentorEmail: '', feeStatus: 'na', totalFee: 0, feePaid: 0, phone: '', guardianName: '', guardianPhone: '', lastResult: '', lastFollowUp: '', nextFollowUp: '', notes: '', status: 'active', createdAt: now, updatedAt: now },
    { id: genId(), name: 'Marvellous Onanubi', level: 'university', school: '', classYear: '400 Level', mentorName: 'Dr. Foluke Otitoju', mentorPhone: '', mentorEmail: '', feeStatus: 'na', totalFee: 0, feePaid: 0, phone: '', guardianName: '', guardianPhone: '', lastResult: '', lastFollowUp: '', nextFollowUp: '', notes: '', status: 'active', createdAt: now, updatedAt: now },
    { id: genId(), name: 'Abiodun Okunola', level: 'university', school: '', classYear: '200 Level', mentorName: 'Ms. Adebola Gbadebo', mentorPhone: '', mentorEmail: '', feeStatus: 'na', totalFee: 0, feePaid: 0, phone: '', guardianName: '', guardianPhone: '', lastResult: '', lastFollowUp: '', nextFollowUp: '', notes: '', status: 'active', createdAt: now, updatedAt: now },
    { id: genId(), name: 'Taiwo Testimony', level: 'university', school: '', classYear: '200 Level', mentorName: 'Dr. Folasade Kehinde', mentorPhone: '', mentorEmail: '', feeStatus: 'na', totalFee: 0, feePaid: 0, phone: '', guardianName: '', guardianPhone: '', lastResult: '', lastFollowUp: '', nextFollowUp: '', notes: '', status: 'active', createdAt: now, updatedAt: now },
    { id: genId(), name: 'Success Oloyede', level: 'university', school: '', classYear: '100 Level', mentorName: '', mentorPhone: '', mentorEmail: '', feeStatus: 'na', totalFee: 0, feePaid: 0, phone: '', guardianName: '', guardianPhone: '', lastResult: '', lastFollowUp: '', nextFollowUp: '', notes: 'Needs mentor assignment', status: 'active', createdAt: now, updatedAt: now },
    { id: genId(), name: 'Taiwo Victor', level: 'university', school: '', classYear: '100 Level', mentorName: '', mentorPhone: '', mentorEmail: '', feeStatus: 'na', totalFee: 0, feePaid: 0, phone: '', guardianName: '', guardianPhone: '', lastResult: '', lastFollowUp: '', nextFollowUp: '', notes: 'Needs mentor assignment', status: 'active', createdAt: now, updatedAt: now },
    // Awaiting
    { id: genId(), name: 'Oluwafemi Oyindotun', level: 'awaiting', school: '', classYear: 'Awaiting Admission', mentorName: '', mentorPhone: '', mentorEmail: '', feeStatus: 'na', totalFee: 0, feePaid: 0, phone: '', guardianName: '', guardianPhone: '', lastResult: '', lastFollowUp: '', nextFollowUp: '', notes: '', status: 'awaiting', createdAt: now, updatedAt: now },
    { id: genId(), name: 'Ayuba Godwin', level: 'awaiting', school: '', classYear: 'Awaiting Admission', mentorName: 'Mr. Dami Gbadebo', mentorPhone: '', mentorEmail: '', feeStatus: 'na', totalFee: 0, feePaid: 0, phone: '', guardianName: '', guardianPhone: '', lastResult: '', lastFollowUp: '', nextFollowUp: '', notes: '', status: 'awaiting', createdAt: now, updatedAt: now },
    // Secondary
    { id: genId(), name: 'Samuel Bessy Ada', level: 'secondary', school: '', classYear: 'JSS 1', mentorName: '', mentorPhone: '', mentorEmail: '', feeStatus: 'na', totalFee: 0, feePaid: 0, phone: '', guardianName: '', guardianPhone: '', lastResult: '', lastFollowUp: '', nextFollowUp: '', notes: '', status: 'active', createdAt: now, updatedAt: now },
    { id: genId(), name: 'Favor Moses Moyosore', level: 'secondary', school: '', classYear: 'JSS 1', mentorName: '', mentorPhone: '', mentorEmail: '', feeStatus: 'na', totalFee: 0, feePaid: 0, phone: '', guardianName: '', guardianPhone: '', lastResult: '', lastFollowUp: '', nextFollowUp: '', notes: '', status: 'active', createdAt: now, updatedAt: now },
    { id: genId(), name: 'Bamidele Oreyomi', level: 'secondary', school: '', classYear: 'JSS 1', mentorName: '', mentorPhone: '', mentorEmail: '', feeStatus: 'na', totalFee: 0, feePaid: 0, phone: '', guardianName: '', guardianPhone: '', lastResult: '', lastFollowUp: '', nextFollowUp: '', notes: '', status: 'active', createdAt: now, updatedAt: now },
    { id: genId(), name: 'Adunola Fadero', level: 'secondary', school: '', classYear: 'JSS 3', mentorName: '', mentorPhone: '', mentorEmail: '', feeStatus: 'na', totalFee: 0, feePaid: 0, phone: '', guardianName: '', guardianPhone: '', lastResult: '', lastFollowUp: '', nextFollowUp: '', notes: '', status: 'active', createdAt: now, updatedAt: now },
    { id: genId(), name: 'Joseph Jethro', level: 'secondary', school: '', classYear: 'SS 1', mentorName: '', mentorPhone: '', mentorEmail: '', feeStatus: 'na', totalFee: 0, feePaid: 0, phone: '', guardianName: '', guardianPhone: '', lastResult: '', lastFollowUp: '', nextFollowUp: '', notes: '', status: 'active', createdAt: now, updatedAt: now },
    { id: genId(), name: 'Ogundele Amirah', level: 'secondary', school: '', classYear: 'SS 1', mentorName: '', mentorPhone: '', mentorEmail: '', feeStatus: 'na', totalFee: 0, feePaid: 0, phone: '', guardianName: '', guardianPhone: '', lastResult: '', lastFollowUp: '', nextFollowUp: '', notes: '', status: 'active', createdAt: now, updatedAt: now },
    { id: genId(), name: 'Agbeze Mercy', level: 'secondary', school: '', classYear: 'SS 1', mentorName: '', mentorPhone: '', mentorEmail: '', feeStatus: 'na', totalFee: 0, feePaid: 0, phone: '', guardianName: '', guardianPhone: '', lastResult: '', lastFollowUp: '', nextFollowUp: '', notes: '', status: 'active', createdAt: now, updatedAt: now },
    { id: genId(), name: 'Adeyemi Mercy', level: 'secondary', school: '', classYear: 'JSS 3', mentorName: '', mentorPhone: '', mentorEmail: '', feeStatus: 'na', totalFee: 0, feePaid: 0, phone: '', guardianName: '', guardianPhone: '', lastResult: '', lastFollowUp: '', nextFollowUp: '', notes: '', status: 'active', createdAt: now, updatedAt: now },
    { id: genId(), name: 'Temitayo Daniel', level: 'secondary', school: '', classYear: 'JSS 3', mentorName: '', mentorPhone: '', mentorEmail: '', feeStatus: 'na', totalFee: 0, feePaid: 0, phone: '', guardianName: '', guardianPhone: '', lastResult: '', lastFollowUp: '', nextFollowUp: '', notes: '', status: 'active', createdAt: now, updatedAt: now },
    { id: genId(), name: 'Balogun Iysah', level: 'secondary', school: '', classYear: 'JSS 2', mentorName: '', mentorPhone: '', mentorEmail: '', feeStatus: 'na', totalFee: 0, feePaid: 0, phone: '', guardianName: '', guardianPhone: '', lastResult: '', lastFollowUp: '', nextFollowUp: '', notes: '', status: 'active', createdAt: now, updatedAt: now },
    { id: genId(), name: 'Salaudeen Aduke', level: 'secondary', school: '', classYear: 'JSS 2', mentorName: '', mentorPhone: '', mentorEmail: '', feeStatus: 'na', totalFee: 0, feePaid: 0, phone: '', guardianName: '', guardianPhone: '', lastResult: '', lastFollowUp: '', nextFollowUp: '', notes: '', status: 'active', createdAt: now, updatedAt: now },
    { id: genId(), name: 'George Rejoice Grace', level: 'secondary', school: '', classYear: 'JSS 2', mentorName: '', mentorPhone: '', mentorEmail: '', feeStatus: 'na', totalFee: 0, feePaid: 0, phone: '', guardianName: '', guardianPhone: '', lastResult: '', lastFollowUp: '', nextFollowUp: '', notes: '', status: 'active', createdAt: now, updatedAt: now },
    { id: genId(), name: 'Ayodele Daniel', level: 'secondary', school: '', classYear: 'SS 3', mentorName: '', mentorPhone: '', mentorEmail: '', feeStatus: 'na', totalFee: 0, feePaid: 0, phone: '', guardianName: '', guardianPhone: '', lastResult: '', lastFollowUp: '', nextFollowUp: '', notes: '', status: 'active', createdAt: now, updatedAt: now },
  ];

  students.save(data);
  localStorage.setItem(SEED_KEY, '1');
  return true;
}
